[tool.bumpversion]
current_version = "0.12.0"

parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:\\+sha\\.                                 # + and . to separate the sha
        (?P<sha>[a-z0-9]+(?:[-_\\.][a-z0-9]+)*)  # optional short_commit_sha, starting with a character or number
    )?                                           # sha section is optional
"""

serialize = [
    "{major}.{minor}.{patch}+sha.{short_commit_sha}",
]

search = "{current_version}"
replace = "{new_version}"
regex = false

ignore_missing_version = false
ignore_missing_files = true

tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
moveable_tags = []

allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []
allow_shell_hooks = false

[tool.bumpversion.parts.branch]
independent = true

[tool.bumpversion.parts.sha]
independent = true


[[tool.bumpversion.files]]
filename = "VERSION"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = ".github/ISSUE_TEMPLATE.md"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "library.properties"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "library.json"
search = "\n  \"version\": \"{current_version}\","
replace = "\n  \"version\": \"{new_version}\","
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "docs/doxyfile"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "src/TinyGsmCommon.h"
