; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mayfly, stonefly
src_dir = examples/logger_test
; build_cache_dir = C:/Users/sdamiano/.platformio/caches
extra_configs =
    pio_common_libdeps.ini
    C:/Users/sdamiano/Documents/GitHub/EnviroDIY/workflows/build_scripts/platformio.ini

[env]
monitor_speed = 115200
framework = arduino
check_tool = cppcheck, clangtidy
lib_ldf_mode = deep+
lib_extra_dirs = .
; custom_shared_lib_deps =

[env:compile_db]
extends = env:mayfly
targets = compiledb
lib_deps =
extra_scripts =
	pre:C:/Users/sdamiano/Documents/GitHub/EnviroDIY/workflows/pioScripts/install_working_dependencies.py
	post:C:/Users/sdamiano/Documents/GitHub/EnviroDIY/workflows/pioScripts/generate_compile_commands.py

[env:working]
upload_port = COM16
monitor_port = COM16
board = mayfly
platform = atmelavr

[env:mayfly]
monitor_speed = 115200
; targets = compiledb
platform = atmelavr
board = mayfly
upload_flags = -V
build_flags =
    ${env.build_flags}
    ; -E -dD

[env:stonefly]
monitor_speed = 921600
platform = atmelsam
board = envirodiy_stonefly_m4
framework = arduino
board_build.variants_dir = ${platformio.core_dir}/variants
build_flags =
    ${env.build_flags}
    ; -E -dD
