name: Build Library Examples

on:
  workflow_call:
    inputs:
      boards_to_build:
        description: "A comma-separated list of PlatformIO board names to build"
        default: ""
        required: false
        type: string
      boards_to_ignore:
        description: "A comma-separated list of PlatformIO board names to ignore. Mutually exclusive with boards_to_build"
        default: ""
        required: false
        type: string
      examples_to_build:
        description: "A comma-separated list of examples to build"
        default: ""
        required: false
        type: string
      examples_to_ignore:
        description: "A comma-separated list of examples to ignore. Mutually exclusive with examples_to_build"
        default: ""
        required: false
        type: string

jobs:
  generate_scripts:
    name: Generate Install and Build Scripts
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, 'ci skip') }}
    outputs:
      arduino_job_matrix: ${{ steps.py_matrix.outputs.arduino_job_matrix }}
      pio_job_matrix: ${{ steps.py_matrix.outputs.pio_job_matrix }}
    env:
      BOARDS_TO_BUILD: ${{ inputs.boards_to_build }}
      BOARDS_TO_IGNORE: ${{ inputs.boards_to_ignore }}
      EXAMPLES_TO_BUILD: ${{ inputs.examples_to_build }}
      EXAMPLES_TO_IGNORE: ${{ inputs.examples_to_ignore }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PlatformIO
        uses: EnviroDIY/setup-platformio-action@v1.0.3

      - name: Generate Platform Installation Script
        id: py_platforms
        run: |
          echo "Generating CI platform configurations"
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/matrix_utils.py -o matrix_utils.py
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/0_setup_ci_platforms.py -o 0_setup_ci_platforms.py
          python -u 0_setup_ci_platforms.py

      - name: Generate Library Installation Script
        id: py_libraries
        run: |
          set -e
          if [ "$RUNNER_DEBUG" = "1" ]; then
              echo "Enabling debugging!"
              set -v
              set -x
          fi
          echo "Generating library and platform installation scripts"
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/matrix_utils.py -o matrix_utils.py
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/0_generate_install_scripts.py -o 0_generate_install_scripts.py
          python -u 0_generate_install_scripts.py

      - name: Generate Example Build Matrices
        id: py_matrix
        run: |
          set -e
          if [ "$RUNNER_DEBUG" = "1" ]; then
              echo "Enabling debugging!"
              set -v
              set -x
          fi

          # Check if using custom generator
          if [ -e continuous_integration/generate_job_matrix.py ]
          then
            echo "Generating job matrix from library-specific CI pipeline code"
            echo "Note: Custom generators should also provide a build_job_matrix.py in continuous_integration/"
            python -u continuous_integration/generate_job_matrix.py
          else
            echo "Generating job matrix from standard modular CI Build Pipeline"

            # Download CI Build Pipeline utilities and scripts
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/matrix_utils.py -o matrix_utils.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/1_configure_matrix.py -o 1_configure_matrix.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/2_parse_inputs.py -o 2_parse_inputs.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/3_build_matrix.py -o 3_build_matrix.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/4_build_jobs.py -o 4_build_jobs.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/5_output_results.py -o 5_output_results.py
            curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/6_cleanup.py -o 6_cleanup.py

            # Run the CI Build Pipeline
            python -u 1_configure_matrix.py
            python -u 2_parse_inputs.py
            python -u 3_build_matrix.py
            python -u 4_build_jobs.py
            python -u 5_output_results.py
            # 6_cleanup.py is skipped in GitHub Actions
          fi

      - name: Store generated examples
        uses: actions/upload-artifact@v7
        with:
          name: generated_scripts
          path: |
            continuous_integration_artifacts/

  determine_library_source:
    name: Determine the source of the testing library
    uses: ./.github/workflows/determine_library_source.yaml

  build_ex_arduino:
    name: Build Examples with Arduino CLI
    needs: [determine_library_source, generate_scripts]
    uses: ./.github/workflows/compile_arduino_cli.yaml
    with:
      library_install_zip: ${{ needs.determine_library_source.outputs.library_install_zip }}
      arduino_job_matrix: ${{ needs.generate_scripts.outputs.arduino_job_matrix }}

  build_pio:
    name: Build Examples with PlatformIO
    needs: [determine_library_source, generate_scripts]
    uses: ./.github/workflows/compile_platformio.yaml
    with:
      library_install_git: ${{ needs.determine_library_source.outputs.library_install_git }}
      pio_job_matrix: ${{ needs.generate_scripts.outputs.pio_job_matrix }}

  beautify_outputs:
    name: Beautify Outputs
    needs: [build_ex_arduino, build_pio]
    runs-on: ubuntu-latest
    if: ${{ always() && ! contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Write the requirements file
        run: |
          echo "wheel" > requirements.txt
          echo "requests" >> requirements.txt
          echo "pandas" >> requirements.txt
          echo "tabulate" >> requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python Dependencies
        id: install_dependencies
        run: |
          pip install -r requirements.txt

      - name: Download All Log Artifacts
        id: download_logs
        uses: actions/download-artifact@v8
        with:
          path: |
            continuous_integration_artifacts/
          pattern: "*_logs"
          merge-multiple: true

      - name: List All Log Artifacts
        run: ls -R continuous_integration_artifacts/

      - name: Beautify Outputs
        id: beautify_outputs
        run: |
          set -e
          if [ "$RUNNER_DEBUG" = "1" ]; then
              echo "Enabling debugging!"
              set -v
              set -x
          fi
          echo "Parsing CI build results and generating reports"
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/matrix_utils.py -o matrix_utils.py
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/build_scripts/parse_test_results.py -o parse_test_results.py
          python parse_test_results.py
