name: Prepare a new release and add release assets

on:
  workflow_call:
    inputs:
      include_dependencies:
        description: 'True to include a zip file with dependencies in the release'
        required: false
        type: boolean
        default: true

env:
  PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}

jobs:

  check_version_number:
    name: Check Version Number
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.set_version.outputs.version }}
      zip_name: ${{ steps.set_version.outputs.zip_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Output the Version Numbers
        id: set_version
        run: |
          echo "::debug::Get the current version number"
          VER=$(cat VERSION)
          ZIP_FILE="${GITHUB_REPOSITORY#*/}_Dependencies_${VER}"
          echo "Version Number: ${VER}"
          echo "Zip Name: ${ZIP_FILE}"
          echo "version=${VER}" >> $GITHUB_OUTPUT
          echo "zip_name=${ZIP_FILE}" >> $GITHUB_OUTPUT

  check_for_dependencies:
    name: Check for any library dependencies
    uses: ./.github/workflows/check_for_dependencies.yaml
    if: ${{ ! failure() && ! cancelled() && inputs.include_dependencies }}

  prepare_assets:
    name: Prepare Release Assets
    runs-on: ubuntu-latest
    needs: [check_version_number, check_for_dependencies]
    if: ${{ ! failure() && ! cancelled() && inputs.include_dependencies && needs.check_for_dependencies.outputs.has_library_dependencies == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Write the requirements file
        run: |
          echo "wheel" > requirements.txt
          echo "adafruit-nrfutil" >> requirements.txt
          echo "platformio" >> requirements.txt
          echo "requests" >> requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install python dependencies, including NRF-Utils needed for Adafruit Feathers
        run: |
          pip install -r requirements.txt

      # We use the `arduino/setup-arduino-cli` action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Generate Library Installation Script
        id: py_libraries
        run: |
          set -e
          if [ "$RUNNER_DEBUG" = "1" ]; then
              echo "Enabling debugging!"
              set -v
              set -x
          fi
          echo "Generating dependency library installation script"
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/scripts/generate_library_installation_script.py -o generate_library_installation_script.py
          python -u generate_library_installation_script.py

      - name: copy scripts into working directory, if needed
        id: copy_scripts
        run: |
          set -e
          if [ "$RUNNER_DEBUG" = "1" ]; then
              echo "Enabling debugging!"
              set -v
              set -x
          fi
          mkdir -p continuous_integration
          mv continuous_integration_artifacts/install-library-libdeps-arduino-cli.sh continuous_integration/install-library-libdeps-arduino-cli.sh
          mv continuous_integration_artifacts/install-example-libdeps-arduino-cli.sh continuous_integration/install-example-libdeps-arduino-cli.sh

      - name: Download Arduino CLI config
        id: cli_config
        run: |
          curl -SL https://raw.githubusercontent.com/EnviroDIY/workflows/main/scripts/arduino_cli.yaml -o continuous_integration/arduino_cli.yaml

      - name: Restore Arduino libraries
        uses: actions/cache/restore@v4
        id: restore_libraries
        with:
          path: |
            home/arduino/user
          key: arduino_libraries-${{ hashFiles('continuous_integration/install-library-libdeps-arduino-cli.sh', 'continuous_integration/install-example-libdeps-arduino-cli.sh') }}

      # Install any library dependencies for the Arduino CLI, iff no cache
      # NOTE: Don't update the dependencies beyond what's in the install script!
      - name: Install the Arduino libraries
        id: install_libraries
        if: ${{ (steps.restore_libraries.outputs.cache-hit != 'true') }}
        run: |
          chmod +x continuous_integration/install-library-libdeps-arduino-cli.sh
          sh continuous_integration/install-library-libdeps-arduino-cli.sh
          chmod +x continuous_integration/install-example-libdeps-arduino-cli.sh
          sh continuous_integration/install-example-libdeps-arduino-cli.sh

      - name: Install the library from the master branch
        id: install_master_library
        run: |
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib install --git-url https://github.com/EnviroDIY/${GITHUB_REPOSITORY#*/} --no-deps

          echo "\e[32mUpdating the library index\e[0m"
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib update-index

          echo "\e[32mListing libraries detected by the Arduino CLI\e[0m"
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib list

          echo "\e[32mListing the contents of the Arduino library directory\e[0m"
          ls home/arduino/user/libraries

      # zip up all the installed libraries
      # need to cd into the pio directory so we don't get extra junk directories
      - name: Zip libraries
        run: |
          echo "::debug::Listing Arduino libraries"
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib list
          echo "::debug::Zipping Arduino libraries"
          cd home/arduino/user/libraries
          zip ${{ needs.check_version_number.outputs.zip_name }}.zip -r .
          mv ${{ needs.check_version_number.outputs.zip_name }}.zip $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ls

      - name: Store generated dependency zip
        uses: actions/upload-artifact@v4
        with:
          name: dependency_zip
          path: |
            ${{ needs.check_version_number.outputs.zip_name }}.zip

      - name: Cache Arduino libraries
        uses: actions/cache/save@v4
        id: cache_libraries
        if: always() && steps.restore_libraries.outputs.cache-hit != 'true'
        with:
          path: |
            home/arduino/user
          key: ${{ steps.restore_libraries.outputs.cache-primary-key }}


  release_with_assets:
    name: Create a Release with Assets
    runs-on: ubuntu-latest
    needs: [check_version_number, prepare_assets, check_for_dependencies]
    if: ${{ ! failure() && ! cancelled() && inputs.include_dependencies && needs.check_for_dependencies.outputs.has_library_dependencies == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get change log entry for release notes
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ChangeLog.md
          version: ${{ needs.check_version_number.outputs.current_version }}
          validation_level: warn

      - name: Download any Dependency Zip
        uses: actions/download-artifact@v4
        with:
          name: dependency_zip
          path: |
            ${{ needs.check_version_number.outputs.zip_name }}.zip

      - name: List directory contents
        run: |
          cd $GITHUB_WORKSPACE
          ls

      # Create a new release with zipped dependencies
      - name: Create Release with Assets
        id: create_release_with_zip
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('v{0}',needs.check_version_number.outputs.current_version) }}
          name: ${{ format('v{0}',needs.check_version_number.outputs.current_version) }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          generate_release_notes: false
          files: ${{ format('*/{0}.zip', needs.check_version_number.outputs.zip_name) }}
          fail_on_unmatched_files: true

  release_simple:
    name: Create a New Release
    runs-on: ubuntu-latest
    needs: [check_version_number, check_for_dependencies]
    if: ${{ ! failure() && ! cancelled() && (! inputs.include_dependencies || needs.check_for_dependencies.outputs.has_library_dependencies == 'false') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get change log entry for release notes
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ChangeLog.md
          version: ${{ needs.check_version_number.outputs.current_version }}
          validation_level: warn

      # Create a new release with no zip
      - name: Create Simple Release
        id: create_bare_release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('v{0}',needs.check_version_number.outputs.current_version) }}
          name: ${{ format('v{0}',needs.check_version_number.outputs.current_version) }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          generate_release_notes: false

  publish:
    name: Publish to PlaformIO
    runs-on: ubuntu-latest
    needs: [release_with_assets, release_simple]
    if: |
      always() &&
      (needs.release_with_assets.result == 'success' || needs.release_with_assets.result == 'skipped') &&
      (needs.release_simple.result == 'success' || needs.release_simple.result == 'skipped') &&
      ! (needs.release_with_assets.result == 'skipped' && needs.release_simple.result == 'skipped')

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PlatformIO
        uses: EnviroDIY/setup-platformio-action@v1.0.2

      # Publish the new release to the PlatformIO package manager
      - name: Publish release to the PlatformIO package manager
        id: publish-pio
        run: pio pkg publish --owner envirodiy --non-interactive
